src/config/routes.rb
Rails.application.routes.draw do
  resources :messages

  get 'products/myproducts', to: 'products#my_products', as: "my_products"
  get 'products/myorders', to: 'products#my_orders', as: "my_orders"

  resources :products
  devise_for :users
  root 'pages#home'
  get 'pages/guide'
  post "products/:id/order", to: "products#place_order", as: "place_order"
  get 'pages/success', to: 'pages#success', as: "order_success"
  post "messages/:id/reply", to: "messages#place_reply", as: "place_reply"
 

  mount ActiveStorageDB::Engine => '/active_storage_db'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

src/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_rich_text :description
  has_one_attached :picture

  enum condition: {
    as_new: 1,
    near_perfect_mint: 2,
    excellent: 3,
    very_good: 4,
    poor: 5
  }

  enum colour: {
    black: 1,
    white: 2,
    grey: 3,
    cream: 4,
    beige: 5,
    baby_blue: 6,
    blue_green: 7,
    royal: 8,
    navy: 9,
    gold: 10,
    yellow: 11,
    silver: 12,
    pink: 13,
    purple: 14,
    red: 15,
    green: 16,
    orange: 17
  }
  
end

src/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy place_order] # call the set_product method before runing show, edit, update and destory place_order actions
  before_action :set_form_vars, only: %i[ new edit ] # call the set_form_vars method before new, edit actions
  before_action :authenticate_user!, except: [:index, :show] # make sure the user is authenticated before running any action except index and show actions
  before_action :authorize_user, only: [:edit, :update, :destory] # only authorized user allows to execute edit,update and destory actions 
  # GET /products or /products.json
  # searching products through title 
  def index
   q = request.query_parameters["q"]
   @products = Product.where("title like ?","%#{q}%")
  end

  # GET /products/1 or /products/1.json
  def show
  end
 
   # find all current user's products
  def my_products
    q = request.query_parameters["q"]
    @products = Product.where("title like ?","%#{q}%").where(user_id: current_user.id)
  end

  # find all current user's orders
  def my_orders
    @orders = Order.where(buyer_id: current_user.id)
  end

  # GET /products/new
  # add a new product
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json

   # create a new product
  def create
    
    @product = Product.new(product_params)
    @product.user = current_user

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json

  # updated the product
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  # delete a product
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # order a product
  def place_order
    Order.create(
      product_id: @product.id,
      seller_id: @product.user_id,
      buyer_id: current_user.id,
      paid: true,
      date: Time.current
    )
    @product.update(sold: true)
    redirect_to order_success_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_form_vars
      @categories = Category.all
      @conditions = Product.conditions.keys
      @colours = Product.colours.keys
    end

    # check if it is an authorized user
    def authorize_user
      if @product.user_id != current_user.id
        flash[:alert] = "You can't do that!"
        redirect_to products_path
      end
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :sold, :category_id, :user_id, :description, :price, :colour, :condition, :listed_date, :picture)
    end
end

src/app/helpers/products_helper.rb
module ProductsHelper
    def format_condtion(condition)
        words = condition.split("_").map do |word| 
            word.capitalize
        end
        words.join(" ")
    end
end

src/app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.select :category_id, @categories.map {|c| [c.name, c.id]} %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :picture, style: "display: block" %>
    <%= form.file_field :picture, accept: "image/png, image/jpg, image/jpeg, image/gif" %>
  </div>

  <div>
    <%= form.label :colour, style: "display: block" %>
    <%= form.select :colour, @colours %>
  </div>

  <div>
    <% @conditions.each do |option| %>
      <%= form.label :condition, format_condtion(option), style: "display: block" %>
      <%= form.radio_button :condition, option %>
    <% end %>
  </div>

  <div>
    <%= form.label :listed_date, style: "display: block" %>
    <%= form.date_field :listed_date %> 
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

src/app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Sold:</strong>
    <%= product.sold %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category_id %>
  </p> 

  <p>
    <strong>User:</strong>
    <%= product.user_id %>
 </p> 

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Colour:</strong>
    <%= product.colour %>
  </p>

  <p>
    <strong>Condition:</strong>
    <%= product.condition %>
  </p>

  <p>
    <strong>Listed date:</strong>
    <%= product.listed_date %>
  </p>

</div>

src/app/views/products/edit.html.erb
<div class="product-editing">
  <h1>Editing product</h1>
  <%= render "form", product: @product %>
</div>
<br>

<div>
  <%= link_to "Show this product", @product, class: "button" %> |
  <%= link_to "Back to products", products_path, class: "button button-primary" %>
</div>

src/app/views/products/index.html.erb
<form class="search-bar" method="get">
  <input class="bar" type="text" name="q" />
  <input type="submit" value="Search" />
</form>
<h1 class="product-subtitle">♣️ WOMAN</h1>
<div class="product-layout">
  <% @products.each do |product| %>
    <div class="image">
    <div class="image-container">
      <% if product.picture.attached? %>
        <%= image_tag product.picture, alt: product.title %>
      <% else %>
        <%= image_tag asset_path ("35.jpg"), alt: product.title %>
      <% end %>
    </div>

      <div class="product-title">
          <%= product.title %>
      </div>

      <p class="price-title">$ <%= product.price %></p>
      <p class="colour-title">Colour: <%= product.colour %></p>
      
      <%= link_to 'Show more', product, class: "button" %>
    </div>
  <% end %>
</div>

src/app/views/products/my_orders.html.erb
<h1 class="messages">My Orders</h1>
 
<div id="my-orders">
<table>
    <tr>
      <th>Product</th>
      <th>Order Date</th>
      <th></th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.product.title %></td>
        <td><%= order.created_at.in_time_zone('Sydney').to_formatted_s(:short) %></td>
        <td><%= link_to "Show product", order.product, class:"button" %></td>
      </tr>
    <% end %>
  </table>
</div>

src/app/views/products/my_products.html.erb
<form class="search-bar" method="get">
  <input class="bar" type="text" name="q" />
  <input type="submit" value="Search" />
</form>
<h1 class="product-subtitle">♣️ MY PRODUCTS</h1>
<div class="product-layout">
  <% @products.each do |product| %>
    <div class="image">
    <div class="image-container">
      <% if product.picture.attached? %>
        <%= image_tag product.picture, alt: product.title %>
      <% else %>
        <%= image_tag asset_path ("35.jpg"), alt: product.title %>
      <% end %>
    </div>

      <div class="product-title">
          <%= product.title %>
      </div>

      <p class="price-title">$ <%= product.price %></p>
      <p class="colour-title">Colour: <%= product.colour %></p>
      
      <%= link_to 'Show more', product, class: "button" %>
    </div>
  <% end %>
</div>

src/app/views/products/new.html.erb
<div class="product-adding">
  <h1>New product</h1>

  <%= render "form", product: @product %>
</div>
<br>

<div>
  <%= link_to "Back to products", products_path, class: "button button-primary" %>
</div>

src/app/views/products/show.html.erb
<div class="show-image">
  <% if @product.picture.attached? %>
    <%= image_tag @product.picture, alt: @product.title %>
  <% else %>
    <%= image_tag asset_path ("35.jpg"), alt: @product.title %>
  <% end %>
</div>


<div class="product-information">
  <%# <%= render @product %> 
    <div class="product-title"><%= @product.title %></div>
    <div>$ <%= @product.price %></div>
    <div><span class="product-subtitle">Colour:</span><%= @product.colour %></div>
    <div><span class="product-condition">Condition: </span><%= format_condtion(@product.condition) %></div>
    <div class="product-description"><%= @product.description %></div>

  <% if current_user != nil && current_user.id == @product.user_id %>
    <%= link_to "Edit", edit_product_path(@product), class: "button" %> 
    <%= button_to "Destroy", @product, method: :delete, class: "button", form: { data: { turbo_confirm: "Are you sure?" } } %>
  <% elsif current_user != nil && !@product.sold %>
    <%= button_to "Buy me!", place_order_path %>
  <% elsif @product.sold %>
    <p class="sold-out">SOLD OUT</p>
  <% end %> 
  <%= link_to "Back", products_path, class: "button" %>
  <% if current_user != nil && current_user.id != @product.user_id %>
    <%= link_to "Contact", new_message_path(:product_id => @product.id ), class: "button" %>
  <% end%>

</div>